### ISSUE TITLE
Admin notice needs to be more descriptive and link to site 

### ISSUE THREAD

**Issue by coenjacobs** [WPupdatePHP/wp-update-php#1]
The [admin notice that gets shown](https://github.com/WPupdatePHP/wp-update-php/blob/ec2f9a85d8ef366b3b48a5a4b9051f5830dd7c2c/src/WPUpdatePhp.php#L52-L56) now is not very descriptive and doesn't link to the website that contains more detailed information. This needs to be improved before the library can be used in live plugins.

**Comment by Rarst** [comment]
[PHP: Supported Versions](http://php.net/supported-versions.php) is good informational page to link to.

**Comment by coenjacobs** [comment]
Added that link to the [homepage of the project](http://www.wpupdatephp.com/). The admin notice needs to link to the "[Time to update](http://www.wpupdatephp.com/update/)" page, so we can change and tweak the information on that page without having to bump this library for every single change.
