### ISSUE TITLE
Offer soft requirement that triggers informative notice

### ISSUE THREAD

**Issue by coenjacobs** [WPupdatePHP/wp-update-php#2]
Plugin should be able to function, but informative notice gets thrown anyway. This to inform people that they are running on an older, unsupported, version of PHP, but don't stop them from using the plugin.

Notice should be dismissible to not annoy people more than we absolutely have to.

**Comment by barrykooij** [comment]
![selfie-1](http://i.imgur.com/xYpPVLQ.gif)

**Comment by dannyvankooten** [comment]
![selfie-0](http://i.imgur.com/zxtYLM2.gif)

**Comment by chrisvanpatten** [comment]
It'd be great if the dismissal bit was optional. For my own plugins, I'd prefer to put the nag up permanently... I know many users just close admin notices and forget they every happened :)

**Comment by coenjacobs** [comment]
Yes, I agree. Have to think about how we can best implement that without adding yet another argument to the constructor. I think passing the recommended version as second argument is fine:

`$updatePhp = new WPUpdatePhp( '5.3.0', '5.4.0' );`

**Comment by afragen** [comment]
> Plugin should be able to function, but informative notice gets thrown anyway. This to inform people that they are running on an older, unsupported, version of PHP, but don't stop them from using the plugin.

But isn't the point of the version check to tell users the plugin will not work under their version of PHP? Wouldn't then loading that plugin cause a fatal?

**Comment by coenjacobs** [comment]
Yes and no. The primary goal of this library is to educate users who run really old PHP versions on why this is a bad thing and tell them what they can do (contact their hosts, ask for upgrade, be happy). In the version that is currently released we can only enforce a minimum version, but the recommended version gives the implementing developer a couple options.

Say they only want to recommend people to upgrade their PHP version, but not enforce it, they can specify PHP 5.2.4 as the minimum required version. The recommended version can be set to whatever they want then, but I'd advice them to always go with PHP 5.4+. In a couple months I will recommend them to go with PHP 5.5+. The reason this is not set in stone somewhere, is because this can be different for each plugin and I want to give them the freedom to do so.

I agree that the [update](http://www.wpupdatephp.com/update/) and [contact your host](http://www.wpupdatephp.com/contact-host/) pages can explain this a bit better. Everybody is more than welcome to propose these changes on the [website repository](https://github.com/WPupdatePHP/WPupdatePHP.github.io) if they like.

**Comment by coenjacobs** [comment]
Closed via #9. The best thing to do for now, I guess. Open for suggestions.
