### ISSUE TITLE
"This plugin" is not clear

### ISSUE THREAD

**Issue by johnbillion** [WPupdatePHP/wp-update-php#7]
Scenario: I bulk activate some plugins, and I end up with an admin message which says "Unfortunately, this plugin can not run on PHP versions older than x.x.x.". Which plugin does it refer to?

**Comment by michaelbeil** [comment]
Good point @johnbillion.

**Comment by coenjacobs** [comment]
Good point again. :) With #2, I'm going to introduce a second parameter to the constructor, but I don't want to add plugin name (and whatever else might come on our path) as parameters as well. Any other ideas to pass the plugin name to the class? A (optional) set method maybe?

**Comment by afragen** [comment]
I think #13 should fix this. Just pass `__FILE__` and compute plugin name.

**Comment by afragen** [comment]
Awaiting other PRs to be included ( or not ) but simple solution is to create another public function that is passed `__FILE__` then sets `$plugin_name` and passes it to `admin_notice`

This would be an optional setting method.
